### ISSUE TITLE
GET Articles queries only return 100 results (Hoaxy API)

### ISSUE THREAD

**Issue by ogelin** [IUNetSci/hoaxy-backend#45] opened 2019-09-11 19:22 UTC
When querying the API, getting articles only return up to 100 results (either the 100 most recent or 100 most relevant results). 

I suggest adding a query param to specify how many results are required. 

This discussion was opened in #28, but should be considered as a separate issue. The inability to obtain all articles corresponding to a query is extremely limiting to API users.

**Comment by filmenczer** [comment] 2019-09-11 20:49
We understand this need. We can consider this request from two perspectives:

1. The version of Hoaxy installed at IU (hoaxy.iuni.iu.edu) must have this limit so that our back-end does not get overwhelmed and is able to respond to queries from the front-end.

2. In the open-source Hoaxy software (this repo), we could consider adding such a parameter, but then there would also have to be a system parameter to set a maximum value allowed (e.g., is the maximum is 100 and you ask for 1000, you would still only get 100 or an error). 

The change described in (2) above would only be useful to someone who deploys their own version of Hoaxy on their servers. @ogelin, would it be a useful addition?

**Comment by ogelin** [comment] 2019-09-13 15:43
2 is still pointless if it's impossible to get all the results. It would be best to at least increase from 100 in both 1 and 2. 100 is very small. I doubt incrementing to 1000 or even 10000 would actually overwhelm the back end. 

I may also recommend updating how the back-end is hosted. Parallel computing would also prevent the system overloading.

**Comment by glciampaglia** [comment] 2019-09-13 17:07
Breaking up the results in smaller subsets (i.e., pagination) would solve the issue. But it would entail a significant intervention on the backend. Unfortunately the middleware we use to implement the API (Flask) does not provide pagination by default. There are third-party extensions that do provide it (e.g. Flask-SQLAlchemy), but in the particular case of the articles endpoint the problem is that the articles are not being fetched directly from the DB. So I suspect that it would still require us to write custom code for it. That's as far as I can tell, of course.

Regardless of whether we want to just add a parameter (per Fil's suggestion), or go for full-blown pagination, I think that giving some way to the user to control the number of results is still a useful feature though, so we should at least discuss whether we can implement _some_ feature that addresses it in the long term.

**Comment by ogelin** [comment] 2019-09-13 20:57
Thanks! At least incrementing the max value would already be helpful. I still find 100 surprisingly small.

**Comment by filmenczer** [comment] 2019-09-17 14:45
We discussed the issue. We are unable to change the number of articles returned by the API on our own installation of Hoaxy. 

@ogelin you are welcome to install Hoaxy on your own server and change the number of results returned. This is a parameter that you will find here: https://github.com/IUNetSci/hoaxy-backend/blob/master/hoaxy/ir/search.py#L148

Closing the issue.

**Closed by filmenczer** 2019-09-17 14:45 UTC
Labels: needs discussion
